services:
    postgres:
      container_name: postgres
      image: postgres:latest
      environment:
        POSTGRES_USER: zanzibar-dag
        POSTGRES_PASSWORD: zanzibar-dag
        POSTGRES_DB: zanzibar-dag
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      mem_limit: 4g
      cpus: 1

    mongodb:
      container_name: mongo
      image: mongo:latest
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db

    redis:
      container_name: redis
      image: redis:latest
      restart: always
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        - redis_data:/data
      ports:
        - "6379:6379"

    roach1:
      image: cockroachdb/cockroach:v23.2.3
      container_name: roach1
      hostname: roach1
      # networks:
      #   - roachnet
      ports:
        - "26257:26257"
        - "8081:8081"
      volumes:
        - roach1:/cockroach/cockroach-data
      command: start \
        --advertise-addr=${HOSTNAME}:26357 \
        --http-addr=${HOSTNAME}:8081 \
        --listen-addr=${HOSTNAME}:26357 \
        --sql-addr=${HOSTNAME}:26257 \
        --insecure \
        --join=${HOSTNAME}:26357,roach2:26357,roach3:26357
volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  roach1:
    driver: local